# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 350)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vlayout_main = QtWidgets.QVBoxLayout()
        self.vlayout_main.setObjectName("vlayout_main")
        self.hlayout_top = QtWidgets.QHBoxLayout()
        self.hlayout_top.setObjectName("hlayout_top")
        self.vlayout_inputs = QtWidgets.QVBoxLayout()
        self.vlayout_inputs.setObjectName("vlayout_inputs")
        self.hlayout_type = QtWidgets.QHBoxLayout()
        self.hlayout_type.setObjectName("hlayout_type")
        self.label_type = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_type.setFont(font)
        self.label_type.setObjectName("label_type")
        self.hlayout_type.addWidget(self.label_type)
        self.combo_type = QtWidgets.QComboBox(Form)
        self.combo_type.setObjectName("combo_type")
        self.hlayout_type.addWidget(self.combo_type)
        self.vlayout_inputs.addLayout(self.hlayout_type)
        self.hlayout_cords = QtWidgets.QHBoxLayout()
        self.hlayout_cords.setObjectName("hlayout_cords")
        self.label_cordinates_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cordinates_2.setFont(font)
        self.label_cordinates_2.setObjectName("label_cordinates_2")
        self.hlayout_cords.addWidget(self.label_cordinates_2)
        self.lineEdit_cordinates = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_cordinates.setFont(font)
        self.lineEdit_cordinates.setObjectName("lineEdit_cordinates")
        self.hlayout_cords.addWidget(self.lineEdit_cordinates)
        self.vlayout_inputs.addLayout(self.hlayout_cords)
        self.hlayout_scale = QtWidgets.QHBoxLayout()
        self.hlayout_scale.setObjectName("hlayout_scale")
        self.label_scale = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_scale.setFont(font)
        self.label_scale.setObjectName("label_scale")
        self.hlayout_scale.addWidget(self.label_scale)
        self.lineEdit_scale = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_scale.setFont(font)
        self.lineEdit_scale.setObjectName("lineEdit_scale")
        self.hlayout_scale.addWidget(self.lineEdit_scale)
        self.vlayout_inputs.addLayout(self.hlayout_scale)
        self.hlayout_top.addLayout(self.vlayout_inputs)
        self.button_show = QtWidgets.QPushButton(Form)
        self.button_show.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        self.button_show.setFont(font)
        self.button_show.setObjectName("button_show")
        self.hlayout_top.addWidget(self.button_show)
        self.vlayout_main.addLayout(self.hlayout_top)
        self.vlayout_bottom = QtWidgets.QVBoxLayout()
        self.vlayout_bottom.setObjectName("vlayout_bottom")
        self.hlayout_map = QtWidgets.QHBoxLayout()
        self.hlayout_map.setObjectName("hlayout_map")
        self.pixmap_map = QtWidgets.QLabel(Form)
        self.pixmap_map.setText("")
        self.pixmap_map.setObjectName("pixmap_map")
        self.hlayout_map.addWidget(self.pixmap_map)
        self.vlayout_bottom.addLayout(self.hlayout_map)
        self.vlayout_main.addLayout(self.vlayout_bottom)
        self.verticalLayout_3.addLayout(self.vlayout_main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Карты"))
        self.label_type.setText(_translate("Form", "Тип карты: "))
        self.label_cordinates_2.setText(_translate("Form", "Координаты: "))
        self.label_scale.setText(_translate("Form", "Масштаб: "))
        self.button_show.setText(_translate("Form", "Показать"))
